### PR TITLE
Albert/fix kick power

### LINKED ISSUE #282: Change strength parameter to chip() and kick() to be a value from 0 to 1 instead of 0 to 255

### PR DESCRIPTION
**Pull request by ashaw596**
Change kick and chip to use floats in range [0,1.0]
closes #282.

### CODE REVIEW

File: soccer/Robot.cpp [hunk 1]
```diff
@@ -337,14 +337,44 @@ void OurRobot::faceNone()
...
-void OurRobot::kick(uint8_t strength)
+void OurRobot::kick(float strength)
+{
+	double maxKick = *config->kicker.maxKick;
+	_kick(roundf(strength*((float)maxKick)));
+
+	*_cmdText << "kick(" << (float)strength*100 << "%)\n";
+}	
+/*
+TODO
```
Comment (justbuchanan) [inline soccer/Robot.cpp]: Want to go ahead and remove this part and save it for a later pull request?

File: soccer/Robot.hpp [hunk 2]
```diff
@@ -244,14 +244,29 @@ class OurRobot: public Robot {
...
 	 */
-	void kick(uint8_t strength);
+	void kick(float strength);
 
 	/**
-	 * enable chip when ready at a given strength
+	 * enable kick when ready at a given strength (0-255)
 	 */
-	void chip(uint8_t strength);
+	void kickLevel(unsigned char strength);
```
Comment (justbuchanan) [inline soccer/Robot.hpp]: Any reason for unsigned char over uint8_t?  It seems like int makes it a little clearer what it's for and it also makes it the same as the corresponding parameter to `chipLevel()`.

File: soccer/RobotConfig.cpp [hunk 3]
```diff
@@ -14,10 +14,12 @@ RobotConfig::PID::PID(Configuration* config, QString prefix):
 
 RobotConfig::Kicker::Kicker(Configuration *config, QString prefix):
 	maxKick(new ConfigDouble(config, QString("%1/maxKick").arg(prefix), 50)),
-	maxChip(new ConfigDouble(config, QString("%1/maxChip").arg(prefix), 50))
+	maxChip(new ConfigDouble(config, QString("%1/maxChip").arg(prefix), 50)),
+	speedToStrength(new ConfigDouble(config, QString("%1/speedToStrength").arg(prefix), 0))
```
Comment (justbuchanan) [inline soccer/RobotConfig.cpp]: Let's remove the speedToStrength stuff too.

**Comment by justbuchanan** [comment]
Travis...
