### PR TITLE
Fix comet trail ghosting to (0, 0)

### LINKED ISSUE #360: When the ball is invalid, its comet trail ghosts to (0, 0)

### PR DESCRIPTION
**Pull request by rk1998**
I added a bool value to make sure the pos.moveTo() runs within the for loop. Now the trail does not ghost to (0,0) when the ball goes invalid.

closes #360

### CODE REVIEW

File: soccer/FieldView.cpp [hunk 1]
```diff
@@ -267,17 +267,30 @@ void FieldView::drawTeamSpace(QPainter& p) {
     // History
     p.setBrush(Qt::NoBrush);
     QPainterPath ballTrail;
+    //ballTrail.moveTo(1,1);
```
Comment (jgkamat) [inline soccer/FieldView.cpp]: Can you remove this?

File: soccer/FieldView.cpp [hunk 2]
```diff
@@ -267,17 +267,30 @@ void FieldView::drawTeamSpace(QPainter& p) {
...
+    bool move = false;
     for (unsigned int i = 0; i < 200 && i < _history->size(); ++i) {
         const LogFrame* oldFrame = _history->at(i).get();
         if (oldFrame && oldFrame->has_ball()) {
             QPointF pos = qpointf(oldFrame->ball().pos());
 
-            if (i == 0)
+            if (pos.y() == 0.0) {
+            	cout << "y is 0"<< endl;
```
Comment (jgkamat) [inline soccer/FieldView.cpp]: x
